[package]
name = "movie-lib-test"
version = "0.1.0"
authors = ["13531586430@163.com <13531586430@163.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# 添加本地依赖
movie_lib = {path = "../movie-lib"}
