[package]
name = "exercise"
version = "0.1.0"
authors = ["13531586430@163.com <13531586430@163.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
